### ISSUE TITLE
Not working via Emulator

### ISSUE THREAD

**Issue by aprooks** [Microsoft/Yams#3] opened 2015-12-02 22:26 UTC
Running host via VS administrator.
Getting this error from yamsWOrker:
```
WaWorkerHost.exe] YamsWorker is running
[WaWorkerHost.exe] DeploymentId is deployment27(88)
[WaWorkerHost.exe] Checking for updates
[WaWorkerHost.exe] Failed to perform update; Exception was: System.UnauthorizedAccessException: Access to the path 'Microsoft.Owin.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)

```

web app itself is being run as separate console application and only if I specify different ports for Owin host and service http endpoint.

**Comment by nehmebilal** [comment] 2015-12-02 22:30
Can you provide more information about the error you're getting?
What version of Azure SDK are you using?

**Comment by aprooks** [comment] 2015-12-02 22:46
SDK version 2.7

**Comment by nehmebilal** [comment] 2015-12-02 22:46
As far as I can tell, it looks like the application you are trying to update is being used by another process. Yams is trying to delete the old version and deploy the new version but it is failing because the binaries are in use. Can you make sure that nothing else is locking the binaries?

**Comment by nehmebilal** [comment] 2015-12-02 22:47
Also the current version of YAMS has been tested with Azure 2.5 but if you are building the source code yourself, 2.7 should work fine as well.

**Comment by aprooks** [comment] 2015-12-02 23:10
seems like debugger of Visual Studio was preventing deletion of Owin.dll

**Comment by nehmebilal** [comment] 2015-12-02 23:16
:+1: 

Feel free to close the issue if the problem is solved.

**Comment by aprooks** [comment] 2015-12-02 23:16
the only issue left is that if I specify ` <InputEndpoint name="HttpIn" protocol="http" port="80" />` it conflicts with application, as it needs 80 protocol as well. 

I have a feeling that's a only due to specifics of emulator and in azure Endpoint config will not block internal apps in a worker, will it?

**Comment by nehmebilal** [comment] 2015-12-02 23:24
`<InputEndpoint name="HttpIn" protocol="http" port="80" />` in service definition opens that port on the worker role where Yams is deployed and any application deployed there should be able to use that same port. It should also work in the emulator. Are you getting errors?

**Comment by aprooks** [comment] 2015-12-02 23:24
yes, access denied

**Comment by nehmebilal** [comment] 2015-12-02 23:25
Still starting VS as admin?

**Comment by aprooks** [comment] 2015-12-02 23:26
yes. I tried using different ports to make sure. So any time http port from service definition is the same as for app, I get access denied from owin

**Comment by nehmebilal** [comment] 2015-12-02 23:28
Hmm, I never had that issue and often run it in emulator. If the port is not the same, it's working fine?

**Comment by remusrg** [comment] 2015-12-02 23:29
It is possible that something else is holding onto port 80.

**Comment by aprooks** [comment] 2015-12-02 23:29
ok, I found something very strange. 
http://prntscr.com/99oauj an instance of an app is started, with an access denied error, and after some time another one is started without this error. When I press "close app"  second instance is being restarted

**Comment by aprooks** [comment] 2015-12-02 23:30
@remusrg no, I have already checked for other apps. There was skype, but I've killed it

**Comment by nehmebilal** [comment] 2015-12-02 23:33
When an app dies, Yams tries to restart it few times before giving up on it (this is configurable).. that's why when you close it manually, yams things it just died

**Comment by aprooks** [comment] 2015-12-02 23:34
and client app could have started between yams restarts. Could not reproduce screenshot, now I always get 
```
Url is: http://192.168.99.1/WebApp/1.2
Available Apis:
GET coinflip/next
GET application/info

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://192.168.99.1:80/WebApp/1.2/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
...
``` 

from webApp

**Comment by remusrg** [comment] 2015-12-02 23:36
I am assuming you also checked for IIS if it's started? That would also run on port 80 by default.

**Comment by aprooks** [comment] 2015-12-02 23:52
bothhttp://prntscr.com/99og65 an example of changing both ports http://prntscr.com/99ohsy the one, who was blocking. http://prntscr.com/99oih1 so whenever I change port in serviceDefinition, emulator starts listening right after starting deploy of the service

**Comment by remusrg** [comment] 2015-12-03 01:05
I thought the emulator is doing some port remapping by default which would prevent this from happening, do you have some special configuration? The other theory is the version of Visual Studio and more specifically the emulator itself. I believe we've only tested with the emulator only VS 2013. If you're using VS 2015 the behavior of the Azure emulator that comes with that might be different?

**Comment by nehmebilal** [comment] 2015-12-03 01:22
I just tested this using the `Etg.Yams.Cloud` sample project in the emulator and the `WebApp` sample app.

The app started successfully right away:
```
Url is: http://myipaddress/hello.webapp/1.0
Available Apis:
GET coinflip/next
GET application/info
WebApp has been started successfully
```

**Comment by aprooks** [comment] 2015-12-03 14:09
I will try again on other PCs this weekend. Will let you know the results

**Comment by nehmebilal** [comment] 2015-12-03 17:06
Sounds good. This issue will be closed in the meantime. Please open a new issue (the more specific the better) if you have problems.

**Closed by nehmebilal** 2015-12-03 17:06 UTC

**Comment by aprooks** [comment] 2015-12-03 23:30
@nehmebilal I can confirm that it is working, but only in express emulator mode.

**Comment by nehmebilal** [comment] 2015-12-04 18:35
Thanks for confirmation @aprooks :+1:
